"""postgres: create user table

Revision ID: 139e537731fe
Revises: d13f86395cea
Create Date: 2023-10-31 02:30:54.372046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139e537731fe'
down_revision = 'd13f86395cea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('user_name', sa.String(length=256), server_default='unknown', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['user_id'])
    op.add_column('todo', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'user_id')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'user_id')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
