"""postgres: fix table

Revision ID: 1885e3c6913d
Revises: ca01e2aa05d2
Create Date: 2023-10-30 23:47:36.751328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1885e3c6913d'
down_revision = 'ca01e2aa05d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['user_id'])
    op.add_column('todo', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('todo_user_email_fkey', 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['user_id'])
    op.drop_column('todo', 'user_email')
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('user_name', sa.String(length=256), server_default='unknown', nullable=False))
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'user_id')
    op.add_column('todo', sa.Column('user_email', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key('todo_user_email_fkey', 'todo', 'user', ['user_email'], ['email'])
    op.drop_column('todo', 'user_id')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'user_id')
    # ### end Alembic commands ###
