"""postgres: create todo table

Revision ID: 39679cc997f7
Revises: 93a7693ea2dd
Create Date: 2023-10-27 22:42:06.029297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39679cc997f7'
down_revision = '93a7693ea2dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('deleted', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'deleted')
    # ### end Alembic commands ###
