"""postgres: create todo table

Revision ID: 78474ed3d5af
Revises: 10d0eb272386
Create Date: 2023-10-23 16:37:38.183410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78474ed3d5af'
down_revision = '10d0eb272386'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_id'), 'todo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_id'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
