"""postgres: fix tag table soft delete

Revision ID: 93a7693ea2dd
Revises: 64c2273795e0
Create Date: 2023-10-27 18:39:28.332031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a7693ea2dd'
down_revision = '64c2273795e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('deleted', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'deleted')
    # ### end Alembic commands ###
