"""postgres: create todo tag todo-tag table

Revision ID: ed60b9731b70
Revises: 78474ed3d5af
Create Date: 2023-10-24 16:22:57.119770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed60b9731b70'
down_revision = '78474ed3d5af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tag_tag_id'), 'tag', ['tag_id'], unique=False)
    op.create_table('todo_tag',
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.todo_id'], ),
    sa.PrimaryKeyConstraint('todo_id', 'tag_id')
    )
    op.add_column('todo', sa.Column('todo_id', sa.Integer(), nullable=False))
    op.drop_index('ix_todo_id', table_name='todo')
    op.create_index(op.f('ix_todo_todo_id'), 'todo', ['todo_id'], unique=False)
    op.drop_column('todo', 'tag')
    op.drop_column('todo', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('todo', sa.Column('tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_todo_todo_id'), table_name='todo')
    op.create_index('ix_todo_id', 'todo', ['id'], unique=False)
    op.drop_column('todo', 'todo_id')
    op.drop_table('todo_tag')
    op.drop_index(op.f('ix_tag_tag_id'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
